# appveyor config
# based on https://www.appveyor.com/docs/appveyor-yml/
# validated with https://ci.appveyor.com/tools/validate-yaml

version: "{build}"

environment:
  nodejs_version: 9

# fix line endings in Windows
init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm update

build: off

cache:
  - node_modules -> package.json

configuration: build-lint-test

test_script:
  - npm run ci-test

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
