# appveyor config
# based on https://www.appveyor.com/docs/appveyor-yml/
# validated with https://ci.appveyor.com/tools/validate-yaml

version: "{build}"

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

# fix line endings in Windows
init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  - node -v
  - npm -v
  - npm config set package-lock false
  - npm update --save-dev # https://github.com/npm/npm/issues/16901
  - npm update

build: off

configuration: build-lint-test

test_script:
  - npm run ci-test

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true
